name: "Build React Native iOS app"

on: workflow_dispatch
env:
  BUILD_CERTIFICATE_BASE64: ${{ secrets.P12_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  PROVISION_PROFILES_BASE64: ${{ secrets.ADHOC_MOBILEPROVISION_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ruby version
        run: ruby --version
      - name: echo .plist
        run: |
          echo "EXPORT_OPTIONS_PLIST content: ${{ env.EXPORT_OPTIONS_PLIST }}"
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo "EXPORT_OPTS_PATH: $EXPORT_OPTS_PATH"
          echo "$EXPORT_OPTIONS_PLIST" > $EXPORT_OPTS_PATH
          cat $EXPORT_OPTS_PATH

      - name: Install the Apple certificate and provisioning profile
        id: profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          uuid=`grep UUID -A1 -a $PP_PATH | grep -io "[-A-F0-9]\{36\}"`
          echo "uuid=$uuid" >> $GITHUB_OUTPUT

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision    
      - uses: nickwph/apple-provisioning-profile-action@v1
        with:
          profile-base64:  ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      - name: xcode identity
        run: |
          security find-identity -v -p codesigning
      - name: Find provision profile
        run: |
          cd ~/Library/MobileDevice/Provisioning\ Profiles ls
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Enable Corepack
        run: corepack enable
      - name: Run Yarn Install
        run: |
             yarn install
    
      
      - name: Verify CocoaPods Uninstallation
        run: |
          pod --version
          gem list | grep cocoapods
  
      - name: install Cocoapod dependencies
        run: |
             cd ios
             pod install
             
             

      - name: build archive
        run: |
             cd ios
             xcodebuild  -workspace bps.xcworkspace \
             -scheme "bps" \
             -sdk iphoneos \
             -configuration Debug \
             -destination generic/platform=iOS \
              CODE_SIGN_IDENTITY="iPhone Developer" \
             -archivePath $RUNNER_TEMP/bps.xcarchive \
             archive
      - name: echo .plist
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo "$EXPORT_OPTIONS_PLIST" > $EXPORT_OPTS_PATH
          cat $EXPORT_OPTS_PATH
      - name: export ipa
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo "$EXPORT_OPTIONS_PLIST" > $EXPORT_OPTS_PATH
          cat $EXPORT_OPTS_PATH
          xcodebuild -exportArchive \
          -archivePath $RUNNER_TEMP/bps.xcarchive \
          -exportOptionsPlist $EXPORT_OPTS_PATH \
          -exportPath $RUNNER_TEMP/build
      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/bps.ipa
          retention-days: 3
